---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

fileUrl <- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip"
download.file(fileUrl, destfile = "activity.zip")
unzip("activity.zip")
activity<-read.csv("./activity.csv",header=T,stringsAsFactors=F)
activity[,2]<-as.Date(activity[,2]) 

## What is mean total number of steps taken per day?
sum<-tapply(activity[,1],activity[,2],sum) ##steps per day
hist(sum,breaks=20,main="Total number of steps taken each day", col="red") 
Histogram of the total number of steps taken each day.
mean(activity[,1],na.rm=T)
median(activity[,1],na.rm=T)
Mean and Median of the total number of steps taken each day

## What is the average daily activity pattern?
plot(tapply(activity[!is.na(activity[,1]),1],activity[!is.na(activity[,1]),3],mean),type="l",xlab="Interval",ylab="Number of Steps")
which.max(tapply(activity[!is.na(activity[,1]),1],activity[!is.na(activity[,1]),3],mean)) 
The 104th Interval with index 835,on average across all the days in the dataset, contains the maximum number of steps.

## Imputing missing values
missing<-sum(is.na(activity))
missing
The total number of missing values in the dataset is 2304.
Calculate and report the total number of missing values in the dataset. Fill the missing values in the dataset with the mean for that 5-minute interval
mean<-tapply(activity[,1],activity[,3],mean,na.rm=T)
mvp<-which(is.na(activity[,1])) ##missing value position
for (i in 1:length(mvp))
{
activity[mvp[i],1]<-mean[which(activity[mvp[i],3]==rownames(mean))]
}
sum<-tapply(activity[,1],activity[,2],sum)
hist(sum,breaks=20,main="Total number of steps taken each day", col="red") 
mean(activity[,1])
median(activity[,1],na.rm=T)
The histogram becomes larger. The median and mean is the same. This is because I use daily average in that 5-minutes interval to replace the missing date.
 
## Are there differences in activity patterns between weekdays and weekends?
activity$week
Create a new factor variable in the dataset with two levels ¨C ¡°weekday¡± and ¡°weekend¡± indicating whether a given date is a weekday or weekend day.

data$week<-"weekday"
for(i in 288*61){
  ##data[i,]$Week=weekdays(data[i,]$date)
}
5-minute interval (x-axis) and the average number of steps taken, averaged across all weekday days or weekend days (y-axis).

data.weekday<-data.bydate[,1:5]
data.weekend<-data.bydate[,6:7]
for(i in 1:54){
  if(i%%7==6|i%%7==0)
    data.weekend<-data.frame(data.weekend,data.bydate[,i])
  else data.weekday<-data.frame(data.weekday,data.bydate[,i])
}
colnames(data.weekend)<-c(1:16)
colnames(data.weekday)<-c(1:45)
data.weekendave<-rowSums(data.weekend)/16
plot(data.weekendave,type="l",xlab="Interval",ylab="Number of Steps",main="Weekend")
data.weekdayave<-rowSums(data.weekday)/45
plot(data.weekdayave,type="l",xlab="Interval",ylab="Number of Steps",main="weekday")